graphics_toolkit("gnuplot");
x = [-1:0.01:1];
F1 = x.**2;
F2 = x.**3;
F = sum(F1.*F2);
printf("Ortogonalidad: %f\n", F);
figure(1);
clf;
hold on;
plot(x, F1, 'linewidth', 2);
plot(x, F2, 'linewidth', 2);
